// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/AgentID:1.0
//
/***/

final public class AgentID implements org.omg.CORBA.portable.IDLEntity
{
    public
    AgentID()
    {
    }

    public
    AgentID(String name,
            String[] addresses,
            AgentID[] resolvers,
            Property[] userDefinedProperties)
    {
        this.name = name;
        this.addresses = addresses;
        this.resolvers = resolvers;
        this.userDefinedProperties = userDefinedProperties;
    }

    public String name;
    public String[] addresses;
    public AgentID[] resolvers;
    public Property[] userDefinedProperties;
}
