// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/DateTime:1.0
//
/***/

final public class DateTime implements org.omg.CORBA.portable.IDLEntity
{
    public
    DateTime()
    {
    }

    public
    DateTime(short year,
             short month,
             short day,
             short hour,
             short minutes,
             short seconds,
             short milliseconds,
             char typeDesignator)
    {
        this.year = year;
        this.month = month;
        this.day = day;
        this.hour = hour;
        this.minutes = minutes;
        this.seconds = seconds;
        this.milliseconds = milliseconds;
        this.typeDesignator = typeDesignator;
    }

    public short year;
    public short month;
    public short day;
    public short hour;
    public short minutes;
    public short seconds;
    public short milliseconds;
    public char typeDesignator;
}
