// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/Envelope:1.0
//
final public class EnvelopeHelper
{
    public static void
    insert(org.omg.CORBA.Any any, Envelope val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static Envelope
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[12];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "to";
            members[0].type = AgentIDsHelper.type();

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "from";
            members[1].type = OptAgentIDHelper.type();

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "comments";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "aclRepresentation";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "payloadLength";
            members[4].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[5] = new org.omg.CORBA.StructMember();
            members[5].name = "payloadEncoding";
            members[5].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[6] = new org.omg.CORBA.StructMember();
            members[6].name = "date";
            members[6].type = OptDateTimeHelper.type();

            members[7] = new org.omg.CORBA.StructMember();
            members[7].name = "encrypted";
            members[7].type = stringsHelper.type();

            members[8] = new org.omg.CORBA.StructMember();
            members[8].name = "intendedReceiver";
            members[8].type = AgentIDsHelper.type();

            members[9] = new org.omg.CORBA.StructMember();
            members[9].name = "received";
            members[9].type = OptReceivedObjectHelper.type();

            members[10] = new org.omg.CORBA.StructMember();
            members[10].name = "transportBehaviour";
            members[10].type = OptTransportBehaviourTypeHelper.type();

            members[11] = new org.omg.CORBA.StructMember();
            members[11].name = "userDefinedProperties";
            members[11].type = orb.create_sequence_tc(0, PropertyHelper.type());

            typeCode_ = orb.create_struct_tc(id(), "Envelope", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:FIPA/Envelope:1.0";
    }

    public static Envelope
    read(org.omg.CORBA.portable.InputStream in)
    {
        Envelope _ob_v = new Envelope();
        _ob_v.to = AgentIDsHelper.read(in);
        _ob_v.from = OptAgentIDHelper.read(in);
        _ob_v.comments = in.read_string();
        _ob_v.aclRepresentation = in.read_string();
        _ob_v.payloadLength = in.read_long();
        _ob_v.payloadEncoding = in.read_string();
        _ob_v.date = OptDateTimeHelper.read(in);
        _ob_v.encrypted = stringsHelper.read(in);
        _ob_v.intendedReceiver = AgentIDsHelper.read(in);
        _ob_v.received = OptReceivedObjectHelper.read(in);
        _ob_v.transportBehaviour = OptTransportBehaviourTypeHelper.read(in);
        int len0 = in.read_ulong();
        _ob_v.userDefinedProperties = new Property[len0];
        for(int i0 = 0 ; i0 < len0 ; i0++)
            _ob_v.userDefinedProperties[i0] = PropertyHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, Envelope val)
    {
        AgentIDsHelper.write(out, val.to);
        OptAgentIDHelper.write(out, val.from);
        out.write_string(val.comments);
        out.write_string(val.aclRepresentation);
        out.write_long(val.payloadLength);
        out.write_string(val.payloadEncoding);
        OptDateTimeHelper.write(out, val.date);
        stringsHelper.write(out, val.encrypted);
        AgentIDsHelper.write(out, val.intendedReceiver);
        OptReceivedObjectHelper.write(out, val.received);
        OptTransportBehaviourTypeHelper.write(out, val.transportBehaviour);
        int len0 = val.userDefinedProperties.length;
        out.write_ulong(len0);
        for(int i0 = 0 ; i0 < len0 ; i0++)
            PropertyHelper.write(out, val.userDefinedProperties[i0]);
    }
}
