// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/Envelopes:1.0
//
final public class EnvelopesHolder implements org.omg.CORBA.portable.Streamable
{
    public Envelope[] value;

    public
    EnvelopesHolder()
    {
    }

    public
    EnvelopesHolder(Envelope[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = EnvelopesHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        EnvelopesHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return EnvelopesHelper.type();
    }
}
