// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/OptAgentID:1.0
//
final public class OptAgentIDHolder implements org.omg.CORBA.portable.Streamable
{
    public AgentID[] value;

    public
    OptAgentIDHolder()
    {
    }

    public
    OptAgentIDHolder(AgentID[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = OptAgentIDHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        OptAgentIDHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return OptAgentIDHelper.type();
    }
}
