// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/Payload:1.0
//
final public class PayloadHolder implements org.omg.CORBA.portable.Streamable
{
    public byte[] value;

    public
    PayloadHolder()
    {
    }

    public
    PayloadHolder(byte[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = PayloadHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        PayloadHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PayloadHelper.type();
    }
}
