// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/ReceivedObject:1.0
//
/***/

final public class ReceivedObject implements org.omg.CORBA.portable.IDLEntity
{
    public
    ReceivedObject()
    {
    }

    public
    ReceivedObject(String by,
                   String from,
                   DateTime date,
                   String id,
                   String via)
    {
        this.by = by;
        this.from = from;
        this.date = date;
        this.id = id;
        this.via = via;
    }

    public String by;
    public String from;
    public DateTime date;
    public String id;
    public String via;
}
