// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/strings:1.0
//
final public class stringsHolder implements org.omg.CORBA.portable.Streamable
{
    public String[] value;

    public
    stringsHolder()
    {
    }

    public
    stringsHolder(String[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = stringsHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        stringsHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return stringsHelper.type();
    }
}
