// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/DateTime:1.0
//
final public class DateTimeHelper
{
    public static void
    insert(org.omg.CORBA.Any any, DateTime val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static DateTime
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[8];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "year";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_short);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "month";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_short);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "day";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_short);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "hour";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_short);

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "minutes";
            members[4].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_short);

            members[5] = new org.omg.CORBA.StructMember();
            members[5].name = "seconds";
            members[5].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_short);

            members[6] = new org.omg.CORBA.StructMember();
            members[6].name = "milliseconds";
            members[6].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_short);

            members[7] = new org.omg.CORBA.StructMember();
            members[7].name = "typeDesignator";
            members[7].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_char);

            typeCode_ = orb.create_struct_tc(id(), "DateTime", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:FIPA/DateTime:1.0";
    }

    public static DateTime
    read(org.omg.CORBA.portable.InputStream in)
    {
        DateTime _ob_v = new DateTime();
        _ob_v.year = in.read_short();
        _ob_v.month = in.read_short();
        _ob_v.day = in.read_short();
        _ob_v.hour = in.read_short();
        _ob_v.minutes = in.read_short();
        _ob_v.seconds = in.read_short();
        _ob_v.milliseconds = in.read_short();
        _ob_v.typeDesignator = in.read_char();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, DateTime val)
    {
        out.write_short(val.year);
        out.write_short(val.month);
        out.write_short(val.day);
        out.write_short(val.hour);
        out.write_short(val.minutes);
        out.write_short(val.seconds);
        out.write_short(val.milliseconds);
        out.write_char(val.typeDesignator);
    }
}
