// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/Envelope:1.0
//
/***/

final public class Envelope implements org.omg.CORBA.portable.IDLEntity
{
    public
    Envelope()
    {
    }

    public
    Envelope(AgentID[] to,
             AgentID[] from,
             String comments,
             String aclRepresentation,
             int payloadLength,
             String payloadEncoding,
             DateTime[] date,
             String[] encrypted,
             AgentID[] intendedReceiver,
             ReceivedObject[] received,
             Property[][] transportBehaviour,
             Property[] userDefinedProperties)
    {
        this.to = to;
        this.from = from;
        this.comments = comments;
        this.aclRepresentation = aclRepresentation;
        this.payloadLength = payloadLength;
        this.payloadEncoding = payloadEncoding;
        this.date = date;
        this.encrypted = encrypted;
        this.intendedReceiver = intendedReceiver;
        this.received = received;
        this.transportBehaviour = transportBehaviour;
        this.userDefinedProperties = userDefinedProperties;
    }

    public AgentID[] to;
    public AgentID[] from;
    public String comments;
    public String aclRepresentation;
    public int payloadLength;
    public String payloadEncoding;
    public DateTime[] date;
    public String[] encrypted;
    public AgentID[] intendedReceiver;
    public ReceivedObject[] received;
    public Property[][] transportBehaviour;
    public Property[] userDefinedProperties;
}
