// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/FipaMessage:1.0
//
/***/

final public class FipaMessage implements org.omg.CORBA.portable.IDLEntity
{
    public
    FipaMessage()
    {
    }

    public
    FipaMessage(Envelope[] messageEnvelopes,
                byte[] messageBody)
    {
        this.messageEnvelopes = messageEnvelopes;
        this.messageBody = messageBody;
    }

    public Envelope[] messageEnvelopes;
    public byte[] messageBody;
}
