// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/FipaMessage:1.0
//
final public class FipaMessageHolder implements org.omg.CORBA.portable.Streamable
{
    public FipaMessage value;

    public
    FipaMessageHolder()
    {
    }

    public
    FipaMessageHolder(FipaMessage initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = FipaMessageHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        FipaMessageHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return FipaMessageHelper.type();
    }
}
