// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/MTS:1.0
//
final public class MTSHolder implements org.omg.CORBA.portable.Streamable
{
    public MTS value;

    public
    MTSHolder()
    {
    }

    public
    MTSHolder(MTS initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = MTSHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        MTSHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return MTSHelper.type();
    }
}
