// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/OptDateTime:1.0
//
final public class OptDateTimeHolder implements org.omg.CORBA.portable.Streamable
{
    public DateTime[] value;

    public
    OptDateTimeHolder()
    {
    }

    public
    OptDateTimeHolder(DateTime[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = OptDateTimeHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        OptDateTimeHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return OptDateTimeHelper.type();
    }
}
