// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/OptReceivedObject:1.0
//
final public class OptReceivedObjectHolder implements org.omg.CORBA.portable.Streamable
{
    public ReceivedObject[] value;

    public
    OptReceivedObjectHolder()
    {
    }

    public
    OptReceivedObjectHolder(ReceivedObject[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = OptReceivedObjectHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        OptReceivedObjectHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return OptReceivedObjectHelper.type();
    }
}
