// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/OptTransportBehaviourType:1.0
//
final public class OptTransportBehaviourTypeHolder implements org.omg.CORBA.portable.Streamable
{
    public Property[][] value;

    public
    OptTransportBehaviourTypeHolder()
    {
    }

    public
    OptTransportBehaviourTypeHolder(Property[][] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = OptTransportBehaviourTypeHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        OptTransportBehaviourTypeHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return OptTransportBehaviourTypeHelper.type();
    }
}
