// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/Property:1.0
//
/***/

final public class Property implements org.omg.CORBA.portable.IDLEntity
{
    public
    Property()
    {
    }

    public
    Property(String keyword,
             org.omg.CORBA.Any value)
    {
        this.keyword = keyword;
        this.value = value;
    }

    public String keyword;
    public org.omg.CORBA.Any value;
}
