// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/ReceivedObject:1.0
//
final public class ReceivedObjectHolder implements org.omg.CORBA.portable.Streamable
{
    public ReceivedObject value;

    public
    ReceivedObjectHolder()
    {
    }

    public
    ReceivedObjectHolder(ReceivedObject initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ReceivedObjectHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ReceivedObjectHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ReceivedObjectHelper.type();
    }
}
