// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package FIPA;

//
// IDL:FIPA/ReceivedObject:1.0
//
final public class ReceivedObjectHelper
{
    public static void
    insert(org.omg.CORBA.Any any, ReceivedObject val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static ReceivedObject
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[5];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "by";
            members[0].type = URLHelper.type();

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "from";
            members[1].type = URLHelper.type();

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "date";
            members[2].type = DateTimeHelper.type();

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "id";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "via";
            members[4].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            typeCode_ = orb.create_struct_tc(id(), "ReceivedObject", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:FIPA/ReceivedObject:1.0";
    }

    public static ReceivedObject
    read(org.omg.CORBA.portable.InputStream in)
    {
        ReceivedObject _ob_v = new ReceivedObject();
        _ob_v.by = URLHelper.read(in);
        _ob_v.from = URLHelper.read(in);
        _ob_v.date = DateTimeHelper.read(in);
        _ob_v.id = in.read_string();
        _ob_v.via = in.read_string();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, ReceivedObject val)
    {
        URLHelper.write(out, val.by);
        URLHelper.write(out, val.from);
        DateTimeHelper.write(out, val.date);
        out.write_string(val.id);
        out.write_string(val.via);
    }
}
